-- ============================================================
-- ZY-Invest Seed Data  v1.0.0
-- Run AFTER 01_schema.sql, 02_views.sql, 03_rls.sql
-- ============================================================
-- IMPORTANT: Replace password hash with a real bcrypt hash
-- generated by the backend before running in production.
-- Never store plain text passwords.
-- ============================================================

-- ============================================================
-- Fund settings (single row)
-- ============================================================
INSERT INTO fund_settings (
    id, fund_name, inception_date, base_currency,
    fund_type, primary_market, financial_year_end,
    total_units, current_nta, aum, last_nta_date
) VALUES (
    1, 'ZY-Invest', '2021-12-13', 'MYR',
    'Private Equity Fund', 'Bursa Malaysia', '11-30',
    938534.808200, 1.024519, 961707.20, '2026-03-19'
) ON CONFLICT (id) DO UPDATE SET
    current_nta   = EXCLUDED.current_nta,
    aum           = EXCLUDED.aum,
    last_nta_date = EXCLUDED.last_nta_date,
    updated_at    = NOW();

-- ============================================================
-- Ticker mappings (from Excel holdings)
-- ============================================================
INSERT INTO ticker_map (instrument, yahoo_ticker, asset_class, region, sector, is_manual) VALUES
-- Bursa Malaysia — auto-fetchable
('MYEG',       'MYEG.KL',       'Securities [H]', 'MY', 'Technology',                       FALSE),
('PPHB',       'PPHB.KL',       'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('TRC',        'TRC.KL',        'Securities [H]', 'MY', 'Construction',                     FALSE),
('MPI',        'MPI.KL',        'Securities [H]', 'MY', 'Technology',                       FALSE),
('YTLPOWR',    'YTLPOWR.KL',    'Securities [H]', 'MY', 'Utilities',                        FALSE),
('AWC',        'AWC.KL',        'Securities [M]', 'MY', 'Construction',                     FALSE),
('JTIASA',     'JTIASA.KL',     'Securities [M]', 'MY', 'Plantation',                       FALSE),
('EUPE',       'EUPE.KL',       'Securities [M]', 'MY', 'Property',                         FALSE),
('AMD',        'AMD.KL',        'Securities [H]', 'MY', 'Industrial Products & Services',   FALSE),
('AEONCR',     'AEONCR.KL',     'Securities [L]', 'MY', 'Financial Services',               FALSE),
('ENGTEX',     'ENGTEX.KL',     'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('NOVA',       'NOVA.KL',       'Securities [M]', 'MY', 'Technology',                       FALSE),
('CMSB',       'CMSB.KL',       'Securities [H]', 'MY', 'Construction',                     FALSE),
('UZMA',       'UZMA.KL',       'Securities [M]', 'MY', 'Energy',                           FALSE),
('ULICORP',    'ULICORP.KL',    'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('AGMO',       'AGMO.KL',       'Securities [M]', 'MY', 'Technology',                       FALSE),
('AJI',        'AJI.KL',        'Securities [M]', 'MY', 'Consumer Products',                FALSE),
('BIMB',       'BIMB.KL',       'Securities [L]', 'MY', 'Financial Services',               FALSE),
('KOSSAN',     'KOSSAN.KL',     'Securities [M]', 'MY', 'Health Care',                      FALSE),
('PBBANK',     'PBBANK.KL',     'Securities [L]', 'MY', 'Financial Services',               FALSE),
('MAYBANK',    'MAYBANK.KL',    'Securities [L]', 'MY', 'Financial Services',               FALSE),
('TENAGA',     'TENAGA.KL',     'Securities [M]', 'MY', 'Utilities',                        FALSE),
('INARI',      'INARI.KL',      'Securities [H]', 'MY', 'Technology',                       FALSE),
('FGV',        'FGV.KL',        'Securities [H]', 'MY', 'Plantation',                       FALSE),
('BURSA',      'BURSA.KL',      'Securities [L]', 'MY', 'Financial Services',               FALSE),
('UCHITEC',    'UCHITEC.KL',    'Securities [H]', 'MY', 'Technology',                       FALSE),
('AXREIT',     'AXREIT.KL',     'Real Estate Trust', 'MY', 'REIT',                          FALSE),
('TSH',        'TSH.KL',        'Securities [H]', 'MY', 'Plantation',                       FALSE),
('TDM',        'TDM.KL',        'Securities [M]', 'MY', 'Plantation',                       FALSE),
('LCTITAN',    'LCTITAN.KL',    'Securities [H]', 'MY', 'Industrial Products & Services',   FALSE),
('CIMB',       'CIMB.KL',       'Securities [L]', 'MY', 'Financial Services',               FALSE),
('VS',         'VS.KL',         'Securities [H]', 'MY', 'Industrial Products & Services',   FALSE),
('FFB',        'FFB.KL',        'Securities [M]', 'MY', 'Plantation',                       FALSE),
('AFFIN',      'AFFIN.KL',      'Securities [L]', 'MY', 'Financial Services',               FALSE),
('TAKAFUL',    'TAKAFUL.KL',    'Securities [L]', 'MY', 'Financial Services',               FALSE),
('HARTA',      'HARTA.KL',      'Securities [H]', 'MY', 'Health Care',                      FALSE),
('GASMSIA',    'GASMSIA.KL',    'Securities [H]', 'MY', 'Utilities',                        FALSE),
('GDB',        'GDB.KL',        'Securities [M]', 'MY', 'Construction',                     FALSE),
('TUNEPRO',    'TUNEPRO.KL',    'Securities [M]', 'MY', 'Financial Services',               FALSE),
('SKBSHUT',    'SKBSHUT.KL',    'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('AIMFLEX',    'AIMFLEX.KL',    'Securities [M]', 'MY', 'Technology',                       FALSE),
('MCEMENT',    'MCEMENT.KL',    'Securities [H]', 'MY', 'Construction',                     FALSE),
('OSK',        'OSK.KL',        'Securities [L]', 'MY', 'Financial Services',               FALSE),
('HARBOUR',    'HARBOUR.KL',    'Securities [M]', 'MY', 'Transportation',                   FALSE),
('COASTAL',    'COASTAL.KL',    'Securities [H]', 'MY', 'Energy',                           FALSE),
('MNHLDG',     'MNHLDG.KL',     'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('VERSATL',    'VERSATL.KL',    'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('KSL',        'KSL.KL',        'Securities [M]', 'MY', 'Property',                         FALSE),
('FRONTKEN',   'FRONTKEN.KL',   'Securities [H]', 'MY', 'Technology',                       FALSE),
('TGUAN',      'TGUAN.KL',      'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('MNRB',       'MNRB.KL',       'Securities [L]', 'MY', 'Financial Services',               FALSE),
('GFM',        'GFM.KL',        'Securities [M]', 'MY', 'Construction',                     FALSE),
('PENERGY',    'PENERGY.KL',     'Securities [M]', 'MY', 'Energy',                          FALSE),
('CARIMIN',    'CARIMIN.KL',    'Securities [M]', 'MY', 'Energy',                           FALSE),
('LITRAK',     'LITRAK.KL',     'Securities [H]', 'MY', 'Transportation',                   FALSE),
('TECHBOND',   'TECHBOND.KL',   'Securities [M]', 'MY', 'Industrial Products & Services',   FALSE),
('WELLS',      'WELLS.KL',      'Securities [M]', 'MY', 'Construction',                     FALSE),
('HUAYANG',    'HUAYANG.KL',    'Securities [M]', 'MY', 'Property',                         FALSE),
('SWIFT',      'SWIFT.KL',      'Securities [M]', 'MY', 'Transportation',                   FALSE),
('SUNREIT',    'SUNREIT.KL',    'Real Estate Trust', 'MY', 'REIT',                          FALSE),
('PAVREIT',    'PAVREIT.KL',    'Real Estate Trust', 'MY', 'REIT',                          FALSE),
-- US Stocks — auto-fetchable
('NVDA',       'NVDA',          'Securities [H]', 'US', 'Technology',                       FALSE),
('CVNA',       'CVNA',          'Securities [H]', 'US', 'Consumer Discretionary',           FALSE),
('BNGO',       'BNGO',          'Securities [H]', 'US', 'Health Care',                      FALSE),
-- Manual / OTC / Warrants (no Yahoo ticker)
('MYEG-C6R',   NULL,            'Securities [H]', 'MY', 'Technology',                       TRUE),
('MYEG-C7H',   NULL,            'Securities [H]', 'MY', 'Technology',                       TRUE),
('YTLPOWR-UW', NULL,            'Securities [H]', 'MY', 'Utilities',                        TRUE),
('NOTION-WD',  NULL,            'Securities [M]', 'MY', 'Technology',                       TRUE),
('ENGTEX-WB',  NULL,            'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
('ATECH-WA',   NULL,            'Securities [M]', 'MY', 'Technology',                       TRUE),
('EG-WD',      NULL,            'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
('TTVHB',      NULL,            'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
('MNHLDG-WA',  NULL,            'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
('VERSATL-WA28',NULL,           'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
('FRONTKEN-WB26',NULL,          'Securities [H]', 'MY', 'Technology',                       TRUE),
('TECHBOND-WA25',NULL,          'Securities [M]', 'MY', 'Industrial Products & Services',   TRUE),
-- Singapore / other
('NZY SG Tech Fund', NULL,      'Securities [H]', 'SG', 'Technology',                       TRUE),
-- Unit Trust / Money Market
('United Class-R', NULL,        'Money Market',   'MY', 'Others',                           TRUE),
('USDIF',      NULL,            'Money Market',   'MY', 'Others',                           TRUE),
('MYBC88',     NULL,            'Securities [M]', 'MY', 'Others',                           TRUE),
('MYBC92',     NULL,            'Securities [M]', 'MY', 'Others',                           TRUE)
ON CONFLICT (instrument) DO NOTHING;

-- ============================================================
-- Fee schedules (example — admin should verify/update)
-- ============================================================
-- NOTE: These are placeholder values. Admin must set actual rates
-- via the Fee Schedule admin page after first login.
INSERT INTO fee_schedules (fee_type, rate, basis, hurdle_rate, valid_from, valid_to, description)
VALUES
    ('base',        0.01,  'daily', NULL, '2021-12-13', NULL,
     '1% p.a. base management fee, accrued daily (1/365 per day)'),
    ('performance', 0.20,  'daily', 0.08, '2021-12-13', NULL,
     '20% performance fee on daily excess return above 8% p.a. hurdle')
ON CONFLICT (fee_type, valid_from) DO NOTHING;

-- ============================================================
-- Initial admin user (CHANGE PASSWORD BEFORE GOING LIVE)
-- password_hash below is bcrypt of 'ChangeMe123!' — replace immediately
-- ============================================================
-- INSERT INTO investors (id, name, joined_date) VALUES
--     ('00000000-0000-0000-0000-000000000001', 'Admin', '2021-12-13');
--
-- INSERT INTO users (name, email, password_hash, role, investor_id) VALUES
--     ('ZY Admin', 'admin@zy-invest.com',
--      '$2b$12$PLACEHOLDER_HASH_REPLACE_THIS',
--      'admin',
--      '00000000-0000-0000-0000-000000000001');
--
-- Run this Python snippet to generate a real hash:
--   import bcrypt
--   print(bcrypt.hashpw(b'YourPassword', bcrypt.gensalt()).decode())
